name: Run Build Script

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run_build_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Rclone
        uses: AnimMouse/setup-rclone@v1

      - name: Run Bash script
        env:
          RCLONE_CONFIG_DATA: ${{ secrets.RCLONE_CONFIG }}
          RCLONE_COMMANDS: ${{ secrets.RCLONE_COMMANDS }}
        run: |
          chmod +x ./rclone_executor.sh
          ./rclone_executor.sh
