name: Run Build Script

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run_build_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Bash script
        run: |
          chmod +x ./rclone_executor.sh
          ./rclone_executor.sh
