name: Run Build Script

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run_build_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: registry.gitlab.com
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Run Bash script
        run: |
          docker run -e CONFIG_URL=${{ secrets.CONFIG_URL }} ${{ secrets.DOCKER_IMAGE }} 
